version: "3.9"

services:
  db:
    container_name: db-test-simon-mulquin
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: db-test-simon-mulquin
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
